/**
 * .can3 (Cubism Editor animation project) generator.
 *
 * Generates a .can3 CAFF archive containing animation data that pairs
 * with a .cmo3 model file. Animations drive ParamRotation_* parameters
 * generated by cmo3writer.js.
 *
 * The .can3 format is a CAFF archive (same container as .cmo3) with a
 * single main.xml. Structure reverse-engineered from Hiyori reference:
 *   CAnimation → CSceneSource[] → CMvTrack_Live2DModel_Source
 *     → CMvEffect_Live2DParameter → CMvAttrF[] (Bezier keyframes)
 *
 * @module io/live2d/can3writer
 */

import { XmlBuilder, uuid } from './xmlbuilder.js';
import { emitAllScenes } from './can3/sceneEmit.js';
import { finalizeCan3 } from './can3/finalize.js';

/**
 * Generate a .can3 animation archive.
 *
 * Tracks may take two shapes:
 *   - Node-property track: `{nodeId, property: 'rotation', keyframes}` — the
 *     historical SS form. Maps to a Live2D parameter via the
 *     `deformerParamMap` (groupId → {paramId, min, max, rest?}).
 *   - Parameter track:     `{paramId, min?, max?, rest?, keyframes}` — first-class
 *     Live2D parameter animation, used by the idle generator and any future
 *     AI-driven motion. No `deformerParamMap` entry required.
 *
 * Both shapes coexist in the same animation; the writer collects the union
 * of paramIds across all sources and emits one CMvAttrF per param per scene.
 *
 * @param {object} input
 * @param {object[]} input.animations - SS animations [{name, duration, fps, tracks}]
 * @param {Map<string, {paramId, min, max, rest?}>} input.deformerParamMap - groupId → param info
 * @param {string} input.cmo3FileName - Linked .cmo3 filename (e.g. "model.cmo3")
 * @param {number} input.canvasW
 * @param {number} input.canvasH
 * @param {string} [input.modelName]
 * @returns {Promise<Uint8Array>} .can3 CAFF archive
 */
export async function generateCan3(input) {
  const {
    animations, deformerParamMap,
    cmo3FileName, canvasW, canvasH,
    modelName = 'StretchyStudio Export',
  } = input;

  const x = new XmlBuilder();

  // Shared AdaptType for "Relative"
  const [adaptRel, pidAdaptRel] = x.shared('AdaptType');
  x.sub(adaptRel, 's', { 'xs.n': 'text' }).text = 'Relative';

  // Shared CEffectIds for the three named effects
  const [, pidEffIdParam] = x.shared('CEffectId', { idstr: 'live2dParam' });
  const [, pidEffIdParts] = x.shared('CEffectId', { idstr: 'live2dPartsVisible' });
  const [, pidEffIdVisual] = x.shared('CEffectId', { idstr: 'visualDefault' });

  // Shared CTrackGuid for root track (reused across scenes per Hiyori pattern)
  const [, pidRootTrackGuid] = x.shared('CTrackGuid', { uuid: uuid(), note: 'Root Track' });

  // Resource GUID (links to .cmo3 model)
  const [, pidResourceGuid] = x.shared('CResourceGuid', { uuid: uuid(), note: cmo3FileName });

  // Build the unified set of paramInfo entries: rotation deformer params
  // (from deformerParamMap) plus parameter tracks' paramIds (from any anim).
  // Order is stable: deformer entries first (existing convention), then any
  // additional param-track-only ids in insertion order.
  /** @type {Array<{paramId:string, min:number, max:number, rest:number, sourceGroupId?:string}>} */
  const paramInfoList = [];
  const seenParamIds = new Set();

  for (const [groupId, info] of deformerParamMap) {
    if (seenParamIds.has(info.paramId)) continue;
    seenParamIds.add(info.paramId);
    paramInfoList.push({
      paramId: info.paramId,
      min: info.min, max: info.max, rest: info.rest ?? 0,
      sourceGroupId: groupId,
    });
  }
  for (const anim of animations) {
    for (const t of (anim.tracks ?? [])) {
      if (!t.paramId || seenParamIds.has(t.paramId)) continue;
      seenParamIds.add(t.paramId);
      paramInfoList.push({
        paramId: t.paramId,
        min: t.min ?? -1,
        max: t.max ?? 1,
        rest: t.rest ?? 0,
      });
    }
  }

  // Parameter GUIDs — one per unique paramId across all sources.
  const paramGuids = new Map();
  for (const info of paramInfoList) {
    const [, pid] = x.shared('CParameterGuid', { uuid: uuid(), note: info.paramId });
    paramGuids.set(info.paramId, pid);
  }

  // Per-scene CSceneSource + Root/Model tracks + 5 effects
  const { sceneRefs, sceneGuids, sceneAnimPlaceholders } = emitAllScenes(x, animations, {
    pidAdaptRel, pidEffIdParam, pidEffIdParts, pidEffIdVisual,
    pidRootTrackGuid, pidResourceGuid,
    paramInfoList, paramGuids, deformerParamMap,
    canvasW, canvasH, modelName,
  });

  // CResourceManager + shared CAnimation + main.xml + CAFF pack
  return finalizeCan3(x, {
    pidResourceGuid, cmo3FileName, modelName,
    sceneRefs, sceneGuids, sceneAnimPlaceholders,
  });
}
