// @ts-check

/**
 * V4 Phase 1 — Deformer Info section.
 *
 * Header + per-stage refit toggle, lifted out of `DeformerTab`. The
 * bindings + keyforms readouts move to their own sections so the
 * Properties panel stays sectioned even on a deformer selection.
 *
 * @module v3/editors/properties/sections/DeformerInfoSection
 */

import { useMemo } from 'react';
import { Box, RotateCw, Lock, Unlock } from 'lucide-react';
import { useProjectStore } from '../../../../store/projectStore.js';
import * as SelectImpl from '../../../../components/ui/select.jsx';
import { SectionShell } from './SectionShell.jsx';
import { PropertyRow } from '../primitives/PropertyRow.jsx';

/** @type {Record<string, React.ComponentType<any>>} */
const Sel = /** @type {any} */ (SelectImpl);
const { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } = Sel;

const PARENT_ROOT = '__root__';

/**
 * @param {Object} props
 * @param {string} props.deformerId
 */
export function DeformerInfoSection({ deformerId }) {
  const nodes = useProjectStore((s) => s.project.nodes);
  const updateProject = useProjectStore((s) => s.updateProject);

  const node = useMemo(
    () => (nodes ?? []).find((n) => n?.id === deformerId && n?.type === 'deformer') ?? null,
    [nodes, deformerId],
  );

  const parentOptions = useMemo(
    () => buildParentOptions(nodes, deformerId),
    [nodes, deformerId],
  );

  if (!node) {
    return (
      <SectionShell id="deformerInfo" label="Deformer">
        <div className="text-xs text-muted-foreground">
          Deformer not in project — was it deleted?
        </div>
      </SectionShell>
    );
  }

  const kind = node.deformerKind === 'rotation' ? 'rotation' : 'warp';

  function handleParentChange(newParentValue) {
    const newParent = newParentValue === PARENT_ROOT ? null : newParentValue;
    updateProject((proj) => {
      const target = proj.nodes.find((n) => n?.id === deformerId);
      if (target) target.parent = newParent;
    });
  }

  function toggleUserAuthored() {
    updateProject((proj) => {
      const target = proj.nodes.find((n) => n?.id === deformerId);
      if (!target) return;
      if (target._userAuthored === true) delete target._userAuthored;
      else target._userAuthored = true;
    });
  }

  return (
    <SectionShell
      id="deformerInfo"
      label={kind === 'warp' ? 'Warp Deformer' : 'Rotation Deformer'}
      icon={kind === 'warp' ? <Box size={11} /> : <RotateCw size={11} />}
    >
      <PropertyRow label="ID">
        <code className="text-[11px] text-foreground truncate" title={node.id}>{node.id}</code>
      </PropertyRow>
      <PropertyRow label="Name">
        <span className="text-[11px] text-foreground truncate">{node.name ?? node.id}</span>
      </PropertyRow>
      <PropertyRow label="Parent">
        <Select value={node.parent ?? PARENT_ROOT} onValueChange={handleParentChange}>
          <SelectTrigger className="h-6 text-xs px-2 py-0 w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {parentOptions.map((opt) => (
              <SelectItem key={opt.id} value={opt.id} className="text-xs">
                {opt.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </PropertyRow>

      {kind === 'warp' ? <WarpDetails spec={node} /> : <RotationDetails spec={node} />}

      <button
        onClick={toggleUserAuthored}
        className={`flex items-center justify-between gap-2 text-xs px-2 py-1.5 mt-1 rounded border transition-colors ${
          node._userAuthored === true
            ? 'bg-amber-500/15 border-amber-500/40 text-amber-300 hover:bg-amber-500/20'
            : 'bg-card/30 border-border text-foreground hover:bg-card/50'
        }`}
        title={node._userAuthored === true
          ? 'Currently locked from refit. Re-running Init Rig / per-stage refit will preserve this deformer\'s keyforms and bindings as-is. Click to unlock.'
          : 'Currently regenerated by Init Rig / per-stage refit. Lock to preserve hand-edited keyforms and bindings across re-rigs. Click to lock.'}
      >
        <span className="text-[11px] flex items-center gap-1.5">
          {node._userAuthored === true ? <Lock size={11} /> : <Unlock size={11} />}
          {node._userAuthored === true ? 'Locked from refit' : 'Auto-regenerate by refit'}
        </span>
        <span className="text-[10px] uppercase tracking-wide opacity-70">
          {node._userAuthored === true ? 'click to unlock' : 'click to lock'}
        </span>
      </button>
    </SectionShell>
  );
}

/**
 * @param {Array<object>|undefined|null} nodes
 * @param {string} selfId
 * @returns {Array<{id:string,label:string}>}
 */
function buildParentOptions(nodes, selfId) {
  /** @type {Array<{id:string,label:string}>} */
  const out = [{ id: PARENT_ROOT, label: 'root' }];
  if (!Array.isArray(nodes)) return out;

  /** @type {Set<string>} */
  const descendants = new Set([selfId]);
  let grew = true;
  while (grew) {
    grew = false;
    for (const n of nodes) {
      if (!n || descendants.has(n.id)) continue;
      if (n.parent && descendants.has(n.parent)) {
        descendants.add(n.id);
        grew = true;
      }
    }
  }

  for (const n of nodes) {
    if (!n || !n.id) continue;
    if (descendants.has(n.id)) continue;
    if (n.type !== 'part' && n.type !== 'group' && n.type !== 'deformer') continue;
    const prefix =
      n.type === 'deformer'
        ? (n.deformerKind === 'rotation' ? 'rotation' : 'warp')
        : n.type;
    out.push({ id: n.id, label: `${prefix}: ${n.name ?? n.id}` });
  }
  return out;
}

function WarpDetails({ spec }) {
  const gridSize = spec.gridSize ?? null;
  const firstKf = Array.isArray(spec.keyforms) ? spec.keyforms[0] : null;
  const positionsLen = firstKf?.positions?.length ?? 0;
  return (
    <>
      <PropertyRow label="Grid">
        <span className="text-[11px] text-foreground tabular-nums font-mono">
          {gridSize ? `${gridSize.cols} × ${gridSize.rows}` : '—'}
        </span>
      </PropertyRow>
      <PropertyRow label="Vertices">
        <span className="text-[11px] text-foreground tabular-nums">
          {positionsLen / 2}
        </span>
      </PropertyRow>
    </>
  );
}

function RotationDetails({ spec }) {
  const firstKf = Array.isArray(spec.keyforms) ? spec.keyforms[0] : null;
  const angles = (spec.keyforms ?? [])
    .map((k) => k.angle)
    .filter((a) => typeof a === 'number');
  const angleSummary =
    angles.length === 0 ? '—'
    : angles.length === 1 ? `${angles[0]}°`
    : `${Math.min(...angles)}° → ${Math.max(...angles)}°`;
  return (
    <>
      <PropertyRow label="Origin">
        <span className="text-[11px] text-foreground tabular-nums font-mono">
          {firstKf
            ? `${(firstKf.originX ?? 0).toFixed(2)}, ${(firstKf.originY ?? 0).toFixed(2)}`
            : '—'}
        </span>
      </PropertyRow>
      <PropertyRow label="Angle range">
        <span className="text-[11px] text-foreground tabular-nums font-mono">{angleSummary}</span>
      </PropertyRow>
    </>
  );
}
